// Generated by CoffeeScript 1.3.3
(function() {
  var App;

  App = Ember.Application.create({});

  $(function() {
    return $("#slider").slider({
      value: 100,
      min: 0,
      max: 500,
      step: 50,
      slide: function(event, ui) {
        return console.log("DD");
      }
    });
  });

}).call(this);
